name: 'Setup Cloudflare Warp'
description: 'Sets up and caches the Cloudflare Warp client in your GitHub Actions workflow.'
inputs:
  version:
    description: 'The version of Cloudflare Warp to install'
  organization:
    description: 'The name of your Zero Trust organization'
    required: true
  auth_client_id:
    description: 'The service token client id'
    required: true
  auth_client_secret:
    description: 'The service token client secret'
    required: true
branding:
  icon: 'cloud'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - name: Add apt repo
      run: |
        curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
        sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/cloudflare-client.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
      shell: bash
    - uses: mollerdigital/cache-apt-pkgs-action@master
      with:
        packages: cloudflare-warp
        version: 1.1
    - uses: mollerdigital/setup-cloudflare-warp@cached-apt-install-nix
      with:
        organization: ${{ inputs.organization }}
        auth_client_id: ${{ inputs.auth_client_id }}
        auth_client_secret: ${{ inputs.auth_client_secret }}
